version: "3"

services:
  gateway:
    container_name: gateway
    hostname: gateway
    build: ./gateway
    ports:
      - 80:80
  router:
    container_name: router
    hostname: router
    build: ./router
