version: "3"

services:
  gateway:
    container_name: gateway
    hostname: gateway
    build: ./gateway
    volumes:
      - ./gateway/files:/var/www/localhost/htdocs
    ports:
      - 80:80
  router:
    container_name: router
    hostname: router
    build: ./router
    volumes:
      - ./router/files:/root
  controller:
    container_name: controller
    hostname: controller
    build: ./controller
    volumes:
      - ./controller/files:/root
  database_client:
    container_name: database_client
    hostname: database_client
    build: ./database_client
    volumes:
    - ./database_client/files:/root
  response_formatter:
    container_name: response_formatter
    hostname: response_formatter
    build: ./response_formatter
    volumes:
      - ./response_formatter/files:/root
  database:
    container_name: database
    hostname: database
    build: ./database
