#!/bin/sh

mysqld_safe &
while true; do
    if [ $(mysqladmin status | grep Uptime | wc -l) -ge 1 ]; then
        break
    fi
    sleep 1
done

mysql -u root < /root/schema.sql
mysql -u root < /root/user.sql

tail -f /dev/null
